### ISSUE TITLE
Markers

### ISSUE THREAD

**Issue by KastB** [KIT-ISAS/iviz#1]
Hi,

I searched your repository but have not found any file related to markers.
Is it possible to visualize arbitrary Markers (http://wiki.ros.org/rviz/DisplayTypes/Marker)?
Especially dynamically spawning and visualizing arbitrary meshes would be valuable.

Cheers,
Bernd

**Comment by akzeac** [comment]
Yes, uploading arbitrary meshes is possible by using markers with triangle lists. 
Support for interactive markers is incomplete but I'm working on it.

**Comment by akzeac** [comment]
I'm closing the ticket, but if you have further questions on the marker system feel free to open a new one.
