### ISSUE TITLE
Building .apk application

### ISSUE THREAD

**Issue by LotfiZ** [KIT-ISAS/iviz#4]
Hi dear, 

Firstly i would like to congratulate you on the development of such a game changer app, second i don't know if my question is relevant in this topic so i apologize if it is not.

I have no knowledge of mobile application development so my question is: will the apk for your application be available soon? or would it take the build of the project on unity to output the mobile application?

Regards,
Lotfi

**Comment by akzeac** [comment]
Hi. For the last few weeks I have started uploading an APK in iviz/binaries/android.
I try to keep it up-to-date whenever I change something. You can check it out.
