### ISSUE TITLE
Using IVIZ in Ubuntu Unity

### ISSUE THREAD

**Issue by Hankfirst** [KIT-ISAS/iviz#6]
Thanks for your great job!

My attempt on Windows10 was unsuccessful since the wired connection beteween robot and laptop wire seemed unstable (sometimes the connection can be successful, but most of the time It keeps retrying). So I considered using IVIZ in Ubuntu, but an error occurred when I started UI AR according to the process:

> Assets/Application/Controllers/OccupancyGridListener.cs(4,22): error CS0234: The type or namespace name 'Remoting' does not exist in the namespace 'System.Runtime' (are you missing an assembly reference?)
![DeepinScrot-0353](https://user-images.githubusercontent.com/36870085/104455972-f8cbae80-55e2-11eb-97ee-7e5688d44aae.png)

How should I solve this problem?
Thank you!

**Comment by Hankfirst** [comment]
I solved this problem by commenting the header file reference, but I don’t know if it will bring other troubles. This error did not appear on another laptop with Ubuntu 16.04.

**Comment by akzeac** [comment]
Hi! Thank you. Rider sometimes adds the wrong using directives and I forget to remove them.
Yes, it is safe to comment it out. It should be gone in the latest version.
