### ISSUE TITLE
Cannot find resource 'Controllers/AR'

### ISSUE THREAD

**Issue by Hankfirst** [KIT-ISAS/iviz#7]
Hi,

A problem occurred when I tried to add an AR module:

> InvalidOperationException: Cannot find resource 'Controllers/AR'
Iviz.Resources.Info`1[T].get_Object () (at Assets/Core/ResourceManagers/Info.cs:34)
Iviz.Resources.Info`1[T].Instantiate (UnityEngine.Transform parent) (at Assets/Core/ResourceManagers/Info.cs:96)
Iviz.App.ARModuleData..ctor (Iviz.App.ModuleDataConstructor constructor) (at Assets/Application/Panels/ModuleDatas/ARModuleData.cs:30)
Iviz.App.ModuleData.CreateFromResource (Iviz.App.ModuleDataConstructor c) (at Assets/Application/Panels/ModuleDatas/ModuleData.cs:156)
Iviz.App.ModuleListPanel.CreateModule (Iviz.Resources.Resource+ModuleType resource, System.String topic, System.String type, Iviz.Controllers.IConfiguration configuration, System.String requestedId) (at Assets/Application/Panels/ModuleListPanel.cs:584)
Iviz.App.AddModuleDialogData.OnItemClicked (System.Int32 index, System.String _) (at Assets/Application/Panels/Dialogs/AddModuleDialogData.cs:54)
Iviz.App.ItemListDialogContents.RaiseClicked (System.Int32 id, System.String text) (at Assets/Application/Panels/Dialogs/ItemListDialogContents.cs:225)
Iviz.App.ItemListDialogContents+ItemEntry+<>c__DisplayClass8_0.<.ctor>b__0 () (at Assets/Application/Panels/Dialogs/ItemListDialogContents.cs:88)
UnityEngine.Events.InvokableCall.Invoke () (at <ff7b004c24954ff98f68a709be4708c3>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <ff7b004c24954ff98f68a709be4708c3>:0)
UnityEngine.UI.Button.Press () (at D:/Program Files/Unity/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/UI/Core/Button.cs:68)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at D:/Program Files/Unity/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/UI/Core/Button.cs:110)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at D:/Program Files/Unity/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/ExecuteEvents.cs:50)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at D:/Program Files/Unity/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/ExecuteEvents.cs:261)
UnityEngine.EventSystems.EventSystem:Update() (at D:/Program Files/Unity/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/EventSystem.cs:377)
![QQ截图20210114105758](https://user-images.githubusercontent.com/36870085/104538727-631e3680-5657-11eb-9bf5-dc2ceeee4358.png)

How to solve it? Thanks.

**Comment by akzeac** [comment]
Thank you. I was moving files around and I forgot to update the reference. It should be fixed now.
(Also please not that the AR module doesn't do a lot when started on the PC.)
