### ISSUE TITLE
Parsing ROS_HOSTNAME on mobile phones

### ISSUE THREAD

**Issue by Hankfirst** [KIT-ISAS/iviz#8]
Hi, 
The demonstration of iviz on mobile phones is amazing!  Many thanks for your awesome work!

I have a question about ROS_HOSTNAME and ROS_IP: 

When the ros master is running on the remote robot, the iviz on the phone can obtain ros messages only when ROS_IP is explicitly specified in the robot hosts file.  If just ROS_HOSTNAME is set, then mobile iviz can only get the topic list, which seems to be caused by HOSTNAME not being parsed, as shown in the following screenshot. If it is on a PC, this problem can be easily solved by modifying the local Hosts. But it is difficult to modify Hosts files on Android. Is there a way to directly resolve ROS_HOSTNAME through iviz without specifying ROS_IP in the robot?

![59159fb1d59ad6a74972889b6ab9778](https://user-images.githubusercontent.com/36870085/105356162-065de580-5c2e-11eb-9b1a-7d41acc14526.jpg)

**Comment by akzeac** [comment]
Hi. Sorry for the late reply.
In the latest version, you can set the parameter "/iviz/hosts" in the ROS server with your host aliases.
From the console in the ROS master, you can try for example
rosparam set /iviz/hosts "[['cruiser-kl20', '192.168.0.20']]"
If you have multiple entries, try something like
rosparam set /iviz/hosts  "[['abcd', '192.168.0.21'], ['defg', '192.168.0.22']]"
Then, when you open iviz, in the Console Log dialog you should see something like "Adding custom host A -> B"

I hope this helps you.
